### ISSUE TITLE
contracts.js runtime error regarding BigInt serialize

### ISSUE THREAD

**Issue by stryker99** [Cappinator/bitburner-scripts#1]
RUNTIME ERROR
contracts.js@home (PID - 160)

Do not know how to serialize a BigInt
stack:
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at SolveContract (home/contracts.js:96:19)
    at ProcessContract (home/contracts.js:27:22)
    at FindAndSolveContracts (home/contracts.js:19:13)
    at async main (home/contracts.js:8:3)
    at async R (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:401325)

As far as I can tell there appears to be an issue with the Square Root contract with CSEC. 

I claim to have zero programming knowledge I am just attempting to use your lovely scripts until I can learn how to write javascript myself.

Thank you for these lovely scripts.

**Comment by Cappinator** [comment]
Hi, thanks for your report. seems a new contract type was added by the dev and I didn't check for that in the code. should be fixed now and give an error message cleanly instead of crashing.
